-- ============================================================
-- Copyright (c) 2026 B~CBE Analytics. All rights reserved.
-- Migration 024 — Split Primary into Lower Primary (Grade 1-3)
-- and Upper Primary (Grade 4-6) for subject scoping.
--
-- BACKGROUND
--   019_subjects_section.sql gave every subject a `section` of '',
--   'primary', 'junior-secondary' or 'senior-school', so a subject
--   could be kept out of the picker for levels that never sit it.
--   In practice Primary is not one teaching level: Grade 1-3 and
--   Grade 4-6 run noticeably different subject lists, so a single
--   'primary' scope still left Lower Primary classes being offered
--   Upper Primary subjects (and the other way round).
--
-- WHAT THIS CHANGES
--   Widens the subjects_section_check constraint to also accept
--   'lower-primary' and 'upper-primary'. That is the ONLY change —
--   no data is rewritten.
--
--   'primary' stays valid and keeps its meaning: a subject scoped to
--   'primary' is offered to BOTH Lower and Upper Primary classes, so
--   every subject already scoped that way behaves exactly as it does
--   today. An admin only narrows a subject to one band when they
--   deliberately pick Lower Primary or Upper Primary on the Subjects
--   page.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
--   profiles.section_scope (013_admin_section_scope.sql) and
--   class_section() are NOT touched. A section-scoped admin login is
--   still scoped to Primary / Junior Secondary / Senior School, and a
--   'primary' admin still covers all of Grade 1-6. Splitting an admin
--   login down to a single primary band would mean re-deriving the
--   RLS helper and the published_results policies from 023, and no
--   one has asked for a Lower-Primary-only admin — the split here is
--   about which subjects a class is offered, and about how printed
--   reports label themselves.
--
-- Run this once in Supabase: Dashboard -> SQL Editor -> New query
-- -> paste this whole file -> Run. Safe to run more than once, and
-- safe on an existing install — it only re-defines one CHECK.
-- ============================================================

alter table subjects drop constraint if exists subjects_section_check;
alter table subjects add constraint subjects_section_check
  check (section in ('', 'primary', 'lower-primary', 'upper-primary', 'junior-secondary', 'senior-school'));
